jtype: RocketQAReRanker
with:
  use_cuda: True
  batch_size: 32 #$QUERY_BATCH_SIZE # TODO: set this in py files, this is related to query topk
  init_checkpoint_dir: rocket_qa/checkpoint/marco_cross_encoder_large
meta:
  py_modules: ./rerank.py
