jtype: RocketQAReRanker
with:
  conf_path: models/rocketqa_v1/model/config/ce_config.json
  use_cuda: False
  gpu_card_id: 5
  batch_size: 32 #$QUERY_BATCH_SIZE # TODO: set this in py files, this is related to query topk
meta:
  py_modules: ./rerank.py
