!Flow
version: '1'
executors:
  - name: du_encoder
    uses: DualEncoder
    py_module:
        - executors.py
    uses_with:
        model: v1_marco_de
        use_cuda: $JINA_USE_CUDA
        device_id: 0
        batch_size: 32
    timeout_ready: '-1'
  - name: vec_indexer
    uses: jinahub://SimpleIndexer/v0.9
    uses_metas:
        workspace: $JINA_WORKSPACE
