!Flow
version: '1'
with:
  port_expose: 8886
executors:
  - name: du_encoder
    uses: DualEncoder
    py_module:
        - executors.py
    uses_with:
        model: v1_marco_de
        use_cuda: True
        device_id: 5
        batch_size: 1
  - name: vec_indexer
    uses: jinahub://SimpleIndexer/latest
    uses_with:
        match_args:
            metric: 'cosine'
            limit: 20
    polling: 'ALL'
    uses_after: jinahub://MatchMerger/v0.2
  - name: ranker
    uses: CrossEncoder
    py_module:
        - executors.py
    uses_with:
        model: v1_marco_ce
        use_cuda: True
        device_id: 4
        batch_size: 32
